<a href="https://colab.research.google.com/github/avinue-krixhna/machine-learning/blob/main/01-supervised-learning/regression/04-linear-regression/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**IMPORTING MODULES**

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

**LOADING DATASET**

In [39]:
data = pd.read_csv("insurance.csv")

**PRINTING THE FIRST 5 ROWS DATA FRAME**

In [40]:
data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

**PRINTING THE LAST 5 ROWS**

In [41]:
data.tail()

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [42]:
X = data.iloc[:,: -1]
y = data['charges']

In [43]:
X

      age     sex     bmi  children smoker     region
0      19  female  27.900         0    yes  southwest
1      18    male  33.770         1     no  southeast
2      28    male  33.000         3     no  southeast
3      33    male  22.705         0     no  northwest
4      32    male  28.880         0     no  northwest
...   ...     ...     ...       ...    ...        ...
1333   50    male  30.970         3     no  northwest
1334   18  female  31.920         0     no  northeast
1335   18  female  36.850         0     no  southeast
1336   21  female  25.800         0     no  southwest
1337   61  female  29.070         0    yes  northwest

[1338 rows x 6 columns]

**Encode categorical columns in data**

In [44]:
from sklearn.preprocessing import LabelEncoder


le = LabelEncoder()
data["sex"]= le.fit_transform(data["sex"])
data["smoker"]= le.fit_transform(data["smoker"])
data["region"]= le.fit_transform(data["region"])

**Define X and y from the now-encoded data**

In [45]:
X = data.iloc[:,: -1]
y = data['charges']

**Split Data For Training And Testing**
  (80% for testing and 20% for trainning)

In [46]:
X_test,X_train,y_test,y_train = train_test_split(X,y,test_size = 0.2 , random_state = 42)

**INITIALIZE AND TRAIN THE MODEL**

In [47]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

**PREDICT THE MODEL**

In [48]:
y_predict = model.predict(X_test)

In [49]:
mse = mean_squared_error(y_test, y_predict)
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 38022814.15621111

**CALCULATE THE MEAN**

In [50]:
from sklearn.metrics import mean_squared_error

print(f"Mean Squared Error: {mse}")

Mean Squared Error: 38022814.15621111

In [55]:
import joblib
joblib.dump(model,"linear_regression.pkl")

['linear_regression.pkl']